name: Update Github Activity

on:
  workflow_dispatch:

jobs: 
  update-activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update Github Activity
        uses: TheDanniCraft/activity-log@v1
        with:
          GITHUB_USERNAME: "zac654321"
          GITHUB_TOKEN: ${{ secrets.ACTIONSECRET }}
